site_name: TraceAPI
site_url: https://yang-ze-kang.github.io/TraceAPI/
repo_url: https://github.com/yang-ze-kang/TraceAPI
repo_name: yang-ze-kang/TraceAPI

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: light blue

nav:
  - Home: index.md
  - API Reference: api.md
  - Deployment: deployment.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

